// Chargement des données JSON
// version 2.0
const data = {
    locations: [
    ////////////////////////////////////////////////////////////////////////
    /////////////////// VOLLHEIM
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Handrist",
      "type": "capitale",
      "royaume": "Vollheim",
      "lien": "30",
      "image": "https://i.imgur.com/4dtz46c.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 299,
      "y": 97,
      "description": "Handrist s'offre une vue spectaculaire sur un panorama montagneux à couper le souffle. Les maisons, taillées dans la pierre et l'ardoise, s'intègrent harmonieusement à cet environnement majestueux. Les ruelles pavées serpentent à travers la ville, guidant les visiteurs vers des places animées où les artisans exposent leurs créations artisanales et les tavernes proposent des mets locaux généreux.<br/><br/>Des statues imposantes de dragons, hommage aux ancêtres draconiques de la population, dominent la place centrale. Les rires et les chants des géants et des draconides résonnent dans les artères de la cité, apportant une chaleur humaine à cette atmosphère montagnarde souvent austère. Toutefois, il convient de noter que la vie à Handrist peut être difficile pour les visiteurs non préparés aux rigueurs du climat et qui ne respectent pas les coutumes locales."
    },
    {
      "title": "Forge d’Eldur",
      "type": "zone rp",
      "royaume": "Vollheim",
      "lien": "31",
      "image": "https://i.imgur.com/kBpii4X.jpg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 110,
      "y": 97,
      "description": "La Forge d'Eldur est un lieu sacré au cœur de Vollheim, perchée au sommet d'une montagne qui abrite un volcan actif. C'est ici que les Vollhyr forgent leurs armes, renommées à travers toute Arathia. La chaleur intense de la lave en fusion ne fond pas la neige environnante, créant un saisissant contraste entre le feu et la glace. Les flammes dansent et éclairent les ténèbres, tandis que les marteaux des forgerons résonnent en une symphonie de destruction et de création. Malgré le danger apparent, les Vollhyr peuvent s'approcher de la Forge sans crainte du feu, ayant appris à respecter et à dompter les éléments bruts de la nature.<br/><br/>C'est là que siège la Guilde de la Forge, une imposante structure bâtie directement dans la roche volcanique. Les murs massifs de pierre et les colonnes imposantes donnent l'impression que la guilde est née de la roche elle-même. Des escaliers taillés dans la pierre mènent à différents niveaux de la guilde, où l'on peut observer les maîtres-forgerons en train de façonner les armes et les outils utilisés par les habitants de Vollheim. Les murs sont ornés de symboles et de gravures qui narrent l'histoire de la Forge et de ses maîtres."
    },
    {
      "title": "Forêt de Muspelheim",
      "type": "zone rp",
      "royaume": "Vollheim",
      "lien": "32",
      "image": "https://i.imgur.com/CHWudOu.jpg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 530,
      "y": 275,
      "description": "La Forêt de Muspelheim, nichée dans la clairière de Vollheim, est un site singulier. Contrairement à son nom évoquant une forêt, aucune essence d'arbre ne s'élève à l'horizon. Au lieu de cela, des milliers d'épées de diverses tailles, parmi lesquelles certaines se montrent gigantesques, se dressent ancrées dans le sol, créant l'illusion d'une forêt d'armes. Le mystère plane quant à l'origine de ces épées et la raison de leur implantation en ces lieux.<br/><br/>Malgré cela, les guerriers géants et draconiques accordent un profond respect à cet endroit, y voyant les vestiges d'une bataille légendaire dont les récits se sont perdus au fil du temps. Parmi les lames dressées, plusieurs statues de dragons se dressent fièrement, symboles de puissance et de bravoure, érigées pour honorer les dragons qui auraient combattu aux côtés des géants il y a des siècles. Néanmoins, cette région, bien que fascinante et mystérieuse, demeure périlleuse pour les aventuriers imprudents, car les épées peuvent se fracturer et causer des blessures graves."
    },
    {
      "title": "Chemin de Brattsti",
      "type": "zone rp",
      "royaume": "Vollheim",
      "lien": "34",
      "image": "https://i.imgur.com/rN6be1b.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 422,
      "y": 190,
      "description": "Le Chemin de Brattsti évoque à la fois la crainte et le respect en raison de sa dangerosité incontestable. Il s'étend en un sentier escarpé et périlleux, où chaque pas peut être décisif entre la vie et la mort. Les falaises abruptes, les versants escarpés et les paysages à couper le souffle, bien que hostiles, suscitent admiration et terreur en égal mesure. En dépit des nombreux dangers, le Chemin de Brattsti représente le seul accès menant à Handrist, ce qui le rend incontournable pour les courageux voyageurs et les habitants locaux.<br/><br/>Toutefois, les imprudents ou ceux mal préparés peuvent aisément glisser et chuter dans les précipices. Les tempêtes de neige, les avalanches et les glissements de terrain, fréquents en ces lieux, peuvent être mortels. Par conséquent, prendre les précautions nécessaires avant d'entamer ce trajet est crucial : équipement chaud et imperméable, chaussures robustes, provisions et matériel de secours sont essentiels pour affronter ce chemin redoutable."
    },
    {
      "title": "Rive de Selkryssingr",
      "type": "texte",
      "royaume": "Vollheim",
      "lien": "35",
      "image": "https://i.imgur.com/ONDbIoA.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 654,
      "y": 130,
      "description": "La Rive de Selkryssingr est un passage fluvial entre les montagnes de Vollheim et la forêt d'Arvandor. Le fleuve qui le traverse est large et tumultueux, doté de rapides puissants qui compliquent la navigation. Après la bataille qui s'y est déroulée, les stigmates de la guerre persistent. Les marques sont frappantes : des arbres abattus et consumés, laissant dans la forêt des traces indélébiles. Le sol est entaillé de tranchées, des barricades marquent les rives pour entraver toute traversée ennemie. Des vestiges de fortifications, tours de guet et camps militaires délabrés se dressent encore sur les deux rives.<br/><br/>Les armes terrifiantes ont laissé leur empreinte sur ce lieu, marqué par des terres calcinées et des cratères suite aux explosions. La sève brûlante a altéré arbres, plantes, constructions et faune, contaminés par l'arcanite dorée, dont l'éclat persiste, émettant toujours ses radiations nocives des années après les combats. Les eaux du fleuve ont également été souillées par cette sève, rendant toute vie aquatique impossible. Bien que les années aient passé depuis cette bataille, les séquelles de la guerre demeurent, rappelant aux générations futures les horreurs et les effets désastreux de l'utilisation d'armes destructrices."
    },
    {
      "title": "Royaume de Niflheim",
      "type": "lieu d’intérêt",
      "royaume": "Vollheim",
      "lien": "74",
      "image": "https://i.imgur.com/ABqjbnQ.jpeg",
      "dangerosité": "0",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 226,
      "y": 200,
      "description": "Le Royaume de Niflheim, un sanctuaire vénéré des Vollhyrs, s'ouvre sur une grande salle circulaire, un lieu sacré orné de motifs complexes et de sculptures en relief, témoignant de la richesse de l'héritage spirituel de Vollheim. Au centre de cette salle se dresse un puits énigmatique, ses eaux sombres et impénétrables reflétant la lueur des torches, créant une atmosphère mystique et presque inquiétante.<br/><br/>Considéré comme le point culminant du pouvoir des chamans, ce lieu sacré évoque à la fois respect et solennité. Les Vollhyrs s'y rendent pour honorer leurs défunts, priant dans cette ambiance à la fois solennelle et mystique. On dit que ce puits sans fond est le lien entre le monde des vivants et celui des morts, un symbole de l'union entre les deux. Cette chambre sacrée inspire une vénération profonde et un respect intense pour ceux qui sont passés dans le royaume des esprits."
    },
    {
      "title": "Drekafjöll",
      "type": "lieu d’intérêt",
      "royaume": "Vollheim",
      "lien": "74",
      "image": "https://i.imgur.com/HXAVZ6l.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 550,
      "y": 18,
      "description": "Drekafjöll est une chaîne de montagnes, parmi celles les plus hautes et les plus au nord de Vollheim. Difficiles d'accès même pour les montagnards les plus aguerris, les sommets de Drekafjöll sont autant dangereux que majestueux, véritables témoins de l'histoire ancienne de Vollheim.<br/><br/>Dispersés ça et là dans les montagnes, de nombreux édifices racontent l'histoire de ces hauteurs vertigineuses : repaires de dragons et autres structures liées, la plupart de ces lieux se sont vus réduits à l'état de ruines par le passage du temps. Néanmoins, un explorateur averti pourra trouver ici des traces de l'ancienne race; d'une architecture adaptée à leurs silhouettes massives en passant par leur langage oublié, inscrit dans la roche au détour de quelques écrits et gravures grignotées par l'érosion.<br/><br/>Peuplé d'une faune réminiscente des anciens maîtres des cieux, Drekafjöll regorge de nids à Voldraks, Titano-varans et autres créatures imposantes. Ainsi, entre la difficulté d'accès et la dangerosité des lieux, peu nombreux sont les visiteurs... Sinon ceux assez téméraires pour braver les sommets à la recherche de trésors anciens ou de savoirs oubliés."
    },
    {
      "title": "Ruines de Selkryssingr",
      "type": "lieu d’intérêt",
      "royaume": "Vollheim",
      "lien": "35",
      "image": "https://i.imgur.com/oTBKWFV.jpeg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 560,
      "y": 200,
      "description": "Les Ruines de Selkryssingr se dressent comme des témoins silencieux de la guerre, figées dans le temps et l'histoire. Les vestiges encore imprégnés de l'essence de l'arcanite dorée, se dispersent à perte de vue. Les bâtiments gisent maintenant en ruines, leurs silhouettes déchiquetées témoignant des ravages du conflit passé.<br/><br/>À travers les brèches des murs effondrés, la végétation timidement renaissante tente de reprendre possession de ces lieux autrefois dévastés par la violence. Les herbes folles s'entrelacent aux pierres brisées couvertes d'une neige éternelle, offrant un contraste saisissant entre la vie qui renaît et les cicatrices laissées par la guerre.<br/><br/>Ces ruines sont devenues bien plus qu'un simple vestige de bataille ; elles sont devenues un sanctuaire, un lieu de recueillement où les survivants viennent se souvenir de ceux qui ont péri au combat. Chaque pierre, chaque débris raconte une histoire, rappelant aux générations futures les sacrifices consentis pour la paix et la liberté."
    },
    {
      "title": "Cour des Écailles",
      "type": "lieu d’intérêt",
      "royaume": "Vollheim",
      "lien": "30",
      "image": "https://i.imgur.com/VJzbKJi.jpeg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "béni",
      "x": 377,
      "y": 70,
      "description": "La Cour des Écailles, majestueuse et imposante, se dresse telle une enceinte politique taillée à même la roche des montagnes d'Handrist. Cette vaste salle évoque à la fois la force et la sagesse des draconides qui s'y réunissent régulièrement. Comparable à un parlement, cet espace empreint de solennité est le lieu où se prennent des décisions cruciales pour la communauté draconique.<br/><br/>La lumière naturelle traverse les fenêtres taillées dans la roche, baignant l'intérieur d'une lueur mystique. La Cour des Écailles est le cœur battant de la politique draconique, où se tiennent des débats, des discussions et des délibérations sur les questions les plus pressantes de leur race."
    },
    ////////////////////////////////////////////////////////////////////////
    /////////////////// ARVANDOR
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Arvandor",
      "type": "capitale",
      "royaume": "Arvandor",
      "lien": "36",
      "image": "https://i.imgur.com/3xon3bl.jpg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 970,
      "y": 180,
      "description": "La cité d'Arvandor se dresse majestueusement à l'horizon, avec ses murailles épaisses qui entourent la ville, la protégeant de tous les ennemis. À l'intérieur de ces murs, la ville est un labyrinthe de rues pavées, d'arcades élégantes et de bâtiments grandioses qui racontent l'histoire de la ville et de son peuple.<br/><br/>Au centre de la ville, se trouve le palais royal, une immense structure de pierre blanche qui brille sous les rayons du soleil. Le palais est entouré d'une grande cour ornée de jardins soignés et de fontaines élégantes. Des gardes en armure dorée patrouillent autour de la cour et de la ville, assurant la sécurité de la ville et de ses habitants.<br/><br/>Les rues d'Arvandor sont animées et colorées, avec des étals de marchands vendant toutes sortes de marchandises, des échoppes d'artisans proposant des articles de qualité, et des tavernes bruyantes servant des plats succulents et des boissons rafraîchissantes. Les bâtiments de la ville sont variés, allant des modestes maisons en pierre aux magnifiques manoirs en marbre."
    },
    {
      "title": "Rochebourg",
      "type": "zone rp",
      "royaume": "Arvandor",
      "lien": "37",
      "image": "https://i.imgur.com/bRXVg4b.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 790,
      "y": 230,
      "description": "Parmi les villages qui composent le Royaume d'Arvandor, Rochebourg est probablement l'un des plus typiques. A l'origine Rougebourg, à cause de ses grands champs de coquelicots qui l'entoure, le village est relativement célèbre pour sa production annuelle de coquelicot, fleur nationale du Royaume de l'épée.<br/><br/>Composé d'une petite trentaine de maisons, d'un puits central relié au système d'eau de la capitale et du nécessaire pour vivre en communauté, Rochebourg est traversé par des routes de pierres sur lesquelles passent parfois les convois arvandiens, lorsqu'ils souhaitent prendre un détour plus calme, loin du brouhaha de la route principale vers les autres royaumes. Certains disent même que dans une chambre de l'auberge local, un panneau annoncerait fièrement : « Le Roi d'Arvandor a dormi ici en 43 ». Mythe pour louer la chambre plus chère ou réalité... personne ne le sait vraiment."
    },
    {
      "title": "Avalon",
      "type": "capitale",
      "royaume": "Arvandor",
      "lien": "38",
      "image": "https://i.imgur.com/owMxf73.jpg",
      "dangerosité": "6",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 520,
      "y": 500,
      "description": "Avalon est la capitale côtière du Royaume d'Arvandor, souvent associée à la piraterie et à des pratiques commerciales douteuses. Située sur la côte sud-ouest du royaume, elle est entourée d'un grand port naturel et possède une flotte importante de navires de guerre et de commerce, qui en font une puissance maritime majeure dans la région.La ville est également un important centre commercial, avec un grand marché animé attirant des marchands de tout le continent. La ville est célèbre pour ses produits artisanaux, en particulier ses tissus de soie, ses bijoux et ses épices exotiques. Les rues étroites et sinueuses sont bordées de maisons de pierre et de bois, peintes dans des couleurs vives.<br/><br/>Cependant, la réputation de la ville est entachée par ses pratiques illégales telles que la contrebande, le trafic d'armes et la piraterie. Les rues de la ville sont contrôlées par des gangs et des criminels qui mènent souvent des activités illégales en toute impunité. Le gouvernement d'Arvandor semble tolérer ces pratiques, tant qu'elles ne menacent pas directement la sécurité du royaume.<br/><br/>En raison de son emplacement stratégique et de sa richesse, Avalon est souvent la cible d'attaques de la part de ses voisins et des pirates qui écument les mers. La ville est donc bien défendue, avec une garnison importante et une flotte de navires de guerre prête à intervenir en cas d'attaque. Malgré cette réputation controversée, la ville d'Avalon est également une destination touristique populaire pour ses plages de sable fin, ses eaux cristallines et ses activités nautiques telles que la plongée, la voile et la pêche. La ville possède également plusieurs musées, des galeries d'art et des monuments historiques tels que la tour d'Avalon, qui offre une vue imprenable sur la ville et la baie."
    },
    {
      "title": "Quai de la Hune",
      "type": "zone rp",
      "royaume": "Arvandor",
      "lien": "39",
      "image": "https://i.imgur.com/ljYRTPb.jpg",
      "dangerosité": "3",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 482,
      "y": 550,
      "description": "Situé au bord de la mer de Sylve, le port est un site naturel bien abrité qui s'étend le long d'une grande baie. La ville elle-même est construite sur une colline qui domine la baie, et les rues pavées serpentent en pente douce jusqu'au port. Le port est l'un des plus grands et des plus animés d'Arathia et il est constamment en activité avec des navires venant et partant de toutes les parties du monde.<br/><br/>Le port d'Avalon est équipé de docks et de quais qui permettent d'accueillir une grande variété de navires, des plus petits bateaux de pêche aux grands navires marchands et navires de guerre. La ville est connue pour sa capacité à offrir une gamme de services portuaires tels que la réparation navale, le ravitaillement en eau et en nourriture, ainsi que l'embarquement et le débarquement de marchandises. En conséquence, le commerce maritime est l'une des principales industries de la ville et a contribué à sa croissance économique.<br/><br/>Les quais ont été nommés Quais de la Hune en référence à la célèbre figure de proue sculptée en forme de hibou, qui orne l'entrée du port."
    },
    {
      "title": "Elysium",
      "type": "capitale",
      "royaume": "Arvandor",
      "lien": "40",
      "image": "https://i.imgur.com/Qdw4dkG.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "sacrée",
      "x": 1265,
      "y": 175,
      "description": "Elysium, la cité des célestes, est un royaume suspendu dans les cieux, une île flottante dans un océan éthéré de nuages. Les rayons dorés du soleil jouent avec les reflets cristallins des ruines, illuminant les statues majestueuses en pierre blanche et les fontaines d'eau pure. Les bâtiments, tous plus impressionnants les uns que les autres, rivalisent en hauteur, leurs dômes et leurs tourelles semblant toucher les étoiles elles-mêmes.<br/><br/>L'air est empli d'un parfum suave, porté par les vents de l'aube. Les jardins suspendus, luxuriants et colorés, contrastent avec les vestiges de la guerre passée, rappelant le cycle de la vie et de la mort qui régit tout être vivant. Les voies pavées serpentent entre les bâtiments, éclairées par des lampes magiques et des bougies flottantes, créant une ambiance féerique, malgré la présence oppressante des humains.<br/><br/>Les îles alentour, petites mais charmantes, offrent des paysages pittoresques tels que des jardins flottants et des temples isolés. Les murs de la cité semblent retenir la mer de nuages, créant un horizon infini et éthéré. C'est un lieu où le temps semble suspendu, où l'on peut oublier ses soucis et se perdre dans la contemplation de la beauté divine."
    },
    {
      "title": "Mausolée",
      "type": "zone rp",
      "royaume": "Arvandor",
      "lien": "41",
      "image": "https://i.imgur.com/s571LVG.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "sacrée",
      "x": 1220,
      "y": 200,
      "description": "Le mausolée d'Elysium se dresse fièrement sur la grande île principale, tel un monument intemporel à la mémoire des célestes défunts. Ses murs de marbre blanc s'élèvent vers le ciel, reflétant les rayons dorés du soleil et créant une aura de sérénité. À l'intérieur, les célestes viennent se recueillir devant les tombes ornées de fresques, évoquant les souvenirs et les sacrifices de ceux qui ont péri dans la guerre. Le silence y est presque palpable, seulement rompu par les chuchotements des prières et les murmures des ailes d'ange se déployant doucement. C'est un lieu sacré, empreint de paix et de respect pour les âmes disparues, qui rappelle aux vivants la fragilité de la vie et la nécessité de l'honorer."
    },
    {
      "title": "Marché de la Couronne",
      "type": "lieu d’intérêt",
      "royaume": "Arvandor",
      "lien": "36",
      "image": "https://i.imgur.com/qoIRVwp.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 904,
      "y": 215,
      "description": "Le marché de la couronne est un événement quotidien très populaire dans la ville d'Arvandor. Il se tient sur la grande place centrale de la ville, entourée de bâtiments majestueux et ornée de fontaines en pierre.<br/><br/>Le marché est un lieu de rassemblement pour les habitants de la ville et les visiteurs venus des quatre coins d'Arathia. Dès l'aube, les artisans locaux y exposent leurs produits, allant des bijoux fins aux armures en acier, en passant par les objets en cuir, les sculptures et les poteries. Les étals débordent de couleurs et de textures, attirant les foules venues admirer les merveilles produites par les artisans.<br/><br/>Le marché de la couronne n'est pas seulement un lieu de vente, mais également un lieu de rencontres et de découvertes. Les marchands viennent y discuter affaires, échanger des histoires et se faire des amis. Les voyageurs peuvent y trouver des informations sur leurs futures destinations et les événements à venir dans la ville. Les musiciens de rue ajoutent une ambiance festive avec leurs performances, tandis que les vendeurs de nourriture proposent des plats locaux allant des viandes grillées aux gâteaux sucrés."
    },
    {
      "title": "Les Hauts-quartiers de la Fortune",
      "type": "lieu d’intérêt",
      "royaume": "Arvandor",
      "lien": "38",
      "image": "https://i.imgur.com/nel10DU.jpg",
      "dangerosité": "6",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 503,
      "y": 435,
      "description": "Le marché de la couronne est un événement quotidien très populaire dans la ville d'Arvandor. Il se tient sur la grande place centrale de la ville, entourée de bâtiments majestueux et ornée de fontaines en pierre.<br/><br/>Le marché est un lieu de rassemblement pour les habitants de la ville et les visiteurs venus des quatre coins d'Arathia. Dès l'aube, les artisans locaux y exposent leurs produits, allant des bijoux fins aux armures en acier, en passant par les objets en cuir, les sculptures et les poteries. Les étals débordent de couleurs et de textures, attirant les foules venues admirer les merveilles produites par les artisans.<br/><br/>Le marché de la couronne n'est pas seulement un lieu de vente, mais également un lieu de rencontres et de découvertes. Les marchands viennent y discuter affaires, échanger des histoires et se faire des amis. Les voyageurs peuvent y trouver des informations sur leurs futures destinations et les événements à venir dans la ville. Les musiciens de rue ajoutent une ambiance festive avec leurs performances, tandis que les vendeurs de nourriture proposent des plats locaux allant des viandes grillées aux gâteaux sucrés."
    },

    ////////////////////////////////////////////////////////////////////////
    /////////////////// FANG
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Fang",
      "type": "capitale",
      "royaume": "XingAlda",
      "lien": "42",
      "image": "https://i.imgur.com/1nhDw7h.jpg",
      "dangerosité": "4",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1605,
      "y": 90,
      "description": "Fang, la capitale de Xing Alda, est une ville unique en son genre en raison de son emplacement dans le cratère de l'Étoile, une météorite qui s'est écrasée il y a longtemps sur le pays. La ville est construite en cercle, avec différents quartiers qui varient en fonction de leur profondeur dans le cratère.<br/><br/>Les quartiers les plus hauts se trouvent près de la surface et sont les plus chauds en raison de leur exposition directe au soleil. Ils sont principalement résidentiels et composés de maisons simples et bancales. Au fur et à mesure que l'on descend dans le cratère, les quartiers deviennent plus sombres et plus frais, vu l'absence de soleil, ainsi qu'à une circulation de l'air plus restreinte dans les zones plus profondes. Ces quartiers sont généralement plus densément peuplés et abritent des commerces plus importants, ainsi que les bâtiments publics et officiels tels que le palais de justice et les bâtiments gouvernementaux. Les quartiers les plus bas sont les plus proches de la météorite et les plus luxueux. C'est là que se trouvent les résidences des nobles et des riches commerçants. Ces quartiers sont également les mieux entretenus et les plus décorés, avec des rues pavées de marbre et des fontaines ornées."
    },
    {
      "title": "Académie d'Astrologie",
      "type": "zone rp",
      "royaume": "XingAlda",
      "lien": "43",
      "image": "https://i.imgur.com/Ws9XsS7.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1810,
      "y": 50,
      "description": "L'Académie d'Astrologie est un édifice majestueux situé à quelques kilomètres de Fang, dans le désert de roche rouge. C'est un lieu de savoir et de recherche où les étudiants viennent du monde entier pour étudier l'astronomie, la physique et la cosmologie.<br/><br/>L'académie est construite sur une petite colline qui offre une vue imprenable sur le cratère de la Sainte Sauveuse et les étoiles. Le bâtiment principal est orné de symboles et d'inscriptions en rapport avec l'astronomie. À l'intérieur, il y a des salles de cours, des laboratoires, des observatoires et des bibliothèques contenant des ouvrages rares et précieux.<br/><br/>L'Académie d'Astrologie est dirigée par un directeur respecté dans toute la région pour sa connaissance de l'astronomie. Les étudiants qui y viennent sont très sérieux et motivés pour apprendre, mais certains sont également tentés par les mystères du vide astral qui s'étendent dans le ciel nocturne."
    },
    {
      "title": "Haut Quartier Pauvre",
      "type": "zone rp",
      "royaume": "XingAlda",
      "lien": "44",
      "image": "https://i.imgur.com/8SAFYj4.jpg",
      "dangerosité": "4",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1676,
      "y": 30,
      "description": "Les hauts quartiers de Fang sont une zone densément peuplée, pauvre et souvent dangereuse. La majorité des habitants sont des travailleurs pauvres qui vivent dans des conditions précaires, souvent entassés dans des logements minuscules. Les rues sont étroites et sinueuses, rendant la navigation difficile pour les étrangers et même pour les habitants.<br/><br/>Cependant, malgré sa réputation, les hauts quartiers sont un passage obligatoire pour ceux qui veulent se rendre dans d'autres quartiers ou à la surface. Les commerçants, les aventuriers et les travailleurs empruntent souvent les rues encombrées pour atteindre leurs destinations. Seule la grande route reliant le désert au Quartier Artisanal est réellement praticable.<br/><br/>Malgré les défis de la vie dans les hauts quartiers, les habitants de Fang continuent de s'adapter et de prospérer, même dans les pires conditions."
    },
    {
      "title": "Quartier Artisanal",
      "type": "zone rp",
      "royaume": "XingAlda",
      "lien": "45",
      "image": "https://i.imgur.com/oBjWl2P.jpg",
      "dangerosité": "3",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 1527,
      "y": 50,
      "description": "Le Quartier Artisanal est un lieu très animé où l'on peut trouver toutes sortes de boutiques et d'ateliers artisanaux. Les rues y sont larges et bordées de bâtiments en pierre et en bois, avec des enseignes colorées et des étals de marchands ambulants. On y trouve des artisans de toutes sortes, depuis les forgerons et les armuriers jusqu'aux tisserands et aux joailliers.<br/><br/>Les habitants de Fang sont fiers de leur travail et leur savoir-faire est très apprécié dans toute l'Arathia. On peut y voir des artisans en train de travailler sur des pièces d'armure complexes, des bijoux étincelants et des tissus colorés. Les rues sont souvent remplies d'odeurs alléchantes de nourriture, tant il y a de choses à découvrir.<br/><br/>Les habitants du Quartier Artisanal sont également très fiers de leur quartier et de leur patrimoine. On peut souvent y assister à des festivals et des célébrations organisées dans les rues, avec des danses et des performances pour célébrer l'artisanat local. La plupart des gens sont accueillants et prêts à partager leur passion pour leur métier, et les visiteurs peuvent apprendre beaucoup de choses sur l'artisanat local en discutant avec les habitants."
    },
    {
      "title": "Quartier Noble",
      "type": "zone rp",
      "royaume": "XingAlda",
      "lien": "46",
      "image": "https://i.imgur.com/uqVviOE.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 1558,
      "y": 120,
      "description": "Les quartiers nobles de Fang se trouvent au plus profond de la ville, juste avant La Fosse.<br/><br/>Il s'agit de l'endroit où résident les personnes les plus riches et les plus puissantes de la ville. Les bâtiments y sont les plus grands et les plus luxueux, avec des jardins privés, des fontaines et des sculptures. Les rues sont pavées de pierres précieuses, et les habitants se déplacent dans des calèches tirées par des daoyus.<br/><br/>Les quartiers nobles sont également protégés par une muraille imposante qui entoure l'ensemble de la zone. À l'intérieur, on trouve des palais, des demeures de luxe et des bains publics. Les nobles y organisent des fêtes somptueuses et des banquets extravagants où l'on peut déguster toutes sortes de mets délicieux, notamment des fruits exotiques venus de contrées lointaines.<br/><br/>En somme, les quartiers nobles de Fang sont le symbole de la richesse et de l'opulence des plus grands personnages de la ville."
    },
    {
      "title": "Désert d'Akaara",
      "type": "texte",
      "royaume": "XingAlda",
      "lien": "76",
      "image": "https://i.imgur.com/jIjZGta.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1510,
      "y": 220,
      "description": "Le désert d'Akaara qui entoure le cratère de la météorite est une étendue aride de roches rouges, parsemée de quelques touffes de végétation épineuse qui parviennent à pousser malgré la sécheresse. Les températures peuvent atteindre des niveaux très élevés pendant la journée et chuter rapidement la nuit, ce qui rend les conditions climatiques très difficiles à supporter pour les voyageurs. Les vents y sont souvent violents et soulèvent des nuages de poussière rouge qui peuvent obscurcir le ciel et compliquer la navigation. Les rares oasis dans la région sont de petits points d'eau stagnante, difficiles d'accès et souvent contrôlés par des groupes de nomades ou des bandits, ce qui en fait des lieux dangereux pour les voyageurs imprudents.<br/><br/>Les voyageurs qui s'aventurent dans le désert doivent être prêts à faire face à des tempêtes de sable dévastatrices, des voleurs impitoyables, des bêtes sauvages affamées et des conditions climatiques extrêmes. Seuls les chevaucheurs de tortues sont des experts en survie dans le désert, grâce à leur connaissance des vents de sable et à leur capacité à se protéger des tempêtes meurtrières et à se cacher des Xingbao qui chassent une fois la nuit tombée."
    },    
    {
      "title": "La Fosse",
      "type": "lieu d’intérêt",
      "royaume": "XingAlda",
      "lien": "42",
      "image": "https://i.imgur.com/P5u4PrW.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "gangrénée",
      "x": 1680,
      "y": 110,
      "description": "La Fosse est un lieu sinistre et mystérieux, niché au fond du cratère de l'Étoile, où se trouve la météorite sacrée connue sous le nom de Sainte Sauveuse. C'est un endroit peu fréquentable et effrayant de Fang, car il est dit que des créatures humanoïdes aux allures cadavériques y habitent. Ces créatures sont considérées comme dangereuses et incitent les habitants de Fang à éviter la Fosse et à rester dans les quartiers plus hauts de la ville.<br/><br/>Quoi qu'il en soit, la Fosse est un lieu où il est préférable de ne pas s'attarder si l'on veut préserver sa vie."
    },      
    ////////////////////////////////////////////////////////////////////////
    /////////////////// CERAH
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Arbre Millénaire",
      "type": "capitale",
      "royaume": "Cerah",
      "lien": "48",
      "image": "https://i.imgur.com/qsEylUq.jpg",
      "dangerosité": "0",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "sacrée",
      "x": 1090,
      "y": 500,
      "description": "L'Arbre Millénaire, majestueux et imposant, est le cœur battant d'Arathia. Sa silhouette colossale, à peine discernable depuis le sol, s'élève jusqu'à toucher le ciel et peut être vue depuis tous les coins des royaumes. En son centre, il domine fièrement la forêt dense et luxuriante qui l'entoure, régnant en maître sur les lieux. Il est l'essence même de la vie d'Arathia, la force qui maintient l'équilibre fragile entre la nature et les peuples qui y habitent.<br/><br/>Pourtant, l'Arbre n'a pas toujours été aussi puissant. Pendant l'âge du désespoir, il a été corrompu, ses branches brisées et son tronc dévasté. Mais la vie a repris ses droits, et une grande pousse a récemment émergé, signe de sa renaissance. Même si l'arbre est encore en grande partie vide, la pousse est un espoir, la promesse d'un avenir meilleur.<br/><br/>C'est autour d’une grande table de bois, qui a survécu aux épreuves du temps, que les élus se réunissent. La pousse a transpercé le mobilier pour atteindre la taille d'un arbre déjà imposant, rappelant que la vie continue malgré les épreuves du passé."
    },
    {
      "title": "Bosquet des Anciens",
      "type": "zone rp",
      "royaume": "Cerah",
      "lien": "49",
      "image": "https://i.imgur.com/vTA3iik.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 961,
      "y": 578,
      "description": "Le bosquet des Anciens est un lieu mystérieux, plongé dans l'obscurité de la dense forêt environnante. Des racines noueuses et des lianes entrelacées recouvrent le sol et les arbres, créant un véritable labyrinthe végétal. Le chant des oiseaux et le bruissement des feuilles se mêlent pour créer une ambiance à la fois paisible et étrange. Au fur et à mesure que l'on s'enfonce dans le bosquet, des statues imposantes commencent à apparaître. Sculptées dans une pierre sombre et lisse, elles représentent des créatures inconnues aux formes organiques, avec des branches et des racines qui s'enroulent autour de leurs membres.<br/><br/>Les statues semblent dater de l'ère de la Flore primordiale, et ont été abandonnées depuis longtemps, recouvertes de mousses et de lianes. Des bassins d'eau cristalline sont disséminés dans le bosquet, ajoutant à l'atmosphère mystique du lieu. On peut y voir des poissons nager tranquillement, tandis que des fougères et des plantes aquatiques flottent à la surface. Tout cela donne l'impression d'être dans un lieu figé dans le temps, où la nature a repris ses droits et où les anciens gardiens de la forêt se reposent paisiblement."
    },
    {
      "title": "Orée d'Émeraude",
      "type": "zone rp",
      "royaume": "Cerah",
      "lien": "50",
      "image": "https://i.imgur.com/3AuMEch.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1296,
      "y": 433,
      "description": "L'Orée d'Emeraude est une oasis de civilisation au cœur de la forêt luxuriante de Cerah. Bien que la communauté ne soit pas aussi vaste que les grandes villes des royaumes environnants, elle possède une structure sociale solide et offre un refuge sûr pour les habitants du pays de l'arbre. Le village, construit dans les branches des arbres les plus imposants de la forêt, surplombe majestueusement le bosquet d'Emeraude, qui a donné son nom à la communauté. La construction en hauteur permet de se protéger des prédateurs de la forêt et offre une vue imprenable sur les environs.<br/><br/>Malgré son emplacement éloigné, l'Orée dispose de toutes les commodités nécessaires à la vie quotidienne. Les maisons sont construites dans les arbres les plus hauts et les plus solides, reliées entre elles par des ponts de lianes tressées. Les rues sont étroites mais bien entretenues, et les habitants y vaquent à leurs activités, qu'il s'agisse de commerce, d'artisanat ou d'échanges amicaux."
    },
    {
      "title": "Solaria",
      "type": "zone rp",
      "royaume": "Cerah",
      "lien": "51",
      "image": "https://i.imgur.com/gn8wc9r.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 897,
      "y": 455,
      "description": "Le bosquet de Solaria est un lieu dangereux en raison de la présence d'arcanite dorée sous forme de sève, possédant des propriétés addictives et destructrices. Cette sève est exploitée par Arvandor, qui cherche à l'utiliser comme arme contre la corruption.<br/><br/>Le bosquet lui-même est un endroit envoûtant, avec des arbres immenses qui créent une voûte naturelle permettant à la lumière du soleil de filtrer à travers les feuilles. La sève dorée coule à travers les troncs, donnant l'impression que les arbres sont constellés d'or. Cependant, cette beauté apparente cache une menace insidieuse, rendant l'endroit à la fois fascinant et effrayant.<br/><br/>L'occupation arvandienne et le raffinement industriel de la sève créent une lueur ardente et des émanations qui forment un voile qui s'accumule dans les feuillages, filtrant la lumière du soleil et créant l'illusion que le bosquet se trouve dans un état de stase, toujours au crépuscule. Cette lumière inondant les arbres de couleurs chaudes et apaisantes peut donner un sentiment de calme trompeur alors que la menace de la sève dorée reste très présente, si bien qu'il est conseillé de porter des protections pour le traverser ; et si vous y travaillez, couvrez-vous de la tête aux pieds."
    },
    {
      "title": "Fleurs des Lacs",
      "type": "zone rp",
      "royaume": "Cerah",
      "lien": "52",
      "image": "https://i.imgur.com/pgB2XJD.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "gangrénée",
      "x": 906,
      "y": 740,
      "description": "Le bosquet de la Fleur des Lacs, situé à la frontière sud de Cerah avec le pays des Lacs, est malheureusement corrompu par l'influence des maudits en provenance de la Tour Galate, l'édifice qui domine le pays des Lacs. Cette corruption a transformé la forêt en un lieu sombre et sinistre, reflétant l'atmosphère glauque et morbide qui règne à Ananda.<br/><br/>Le bosquet était autrefois connu pour sa beauté et la variété de ses parterres de fleurs naturels, qui poussait en abondance dans la clairière centrale. Désormais, ces fleurs ont perdu leur éclat et sont souvent associées à la mort et à la corruption.<br/><br/>Les Angias qui vivent près de ce bosquet sont souvent confrontés aux sinistres influences des maudits, qui cherchent à étendre leur influence dans la forêt et à se rapprocher de l’arbre millénaire. Cela crée des tensions entre les deux peuples, lorsque les Angias ne finissent pas par simplement rejoindre la Tour Galate après avoir subit la même corruption que leur bosquet natif."
    },
    {
      "title": "Forêt Troglodyte",
      "type": "zone rp",
      "royaume": "Cerah",
      "lien": "53",
      "image": "https://i.imgur.com/hXKIOaY.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1331,
      "y": 719,
      "description": "Le village troglodyte est un véritable labyrinthe de tunnels, de galeries et de cavernes qui serpentent entre les racines et les pierres. Les parois de roche sont recouvertes d'une mousse sombre et humide, tandis que les racines noueuses forment un réseau complexe qui peut être difficile à naviguer pour les étrangers.<br/><br/>La flore est riche et variée, offrant une gamme de couleurs allant du bleu profond au rose vif. Les mycolux, ces champignons géants, constituent la plus grande source de lumière dans ces endroits obscurs. Leurs chapeaux lumineux projettent des éclats de lumière sur les murs environnants, créant une ambiance féerique qui ne peut être décrite qu'en la voyant de ses propres yeux.<br/><br/>Le village, dissimulé aux yeux des moins curieux, est creusé directement dans les murs de la caverne, avec des portes et des fenêtres en bois sculptées dans la pierre. Des ponts suspendus en bois et en lianes relient les différentes parties du village, permettant aux habitants de se déplacer facilement dans ce dédale souterrain.<br/><br/>En raison de son isolement, peu d'étrangers s'aventurent à explorer la forêt troglodyte. Mais pour ceux qui osent, ils seront récompensés par la découverte d'un monde souterrain mystérieux et étonnant."
    },

    ////////////////////////////////////////////////////////////////////////
    /////////////////// AL'MALAQ
    ////////////////////////////////////////////////////////////////////////

    {
      "title": "Evren",
      "type": "capitale",
      "royaume": "AlMalaq",
      "lien": "67",
      "image": "https://i.imgur.com/fVxmg4W.jpg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 283,
      "y": 715,
      "description": "La ville d'Evren est une cité majestueuse située à la jonction du désert et de l'océan. Elle a été fondée il y a plusieurs siècles et est considérée comme l'une des plus anciennes villes du monde. Elle est le cœur de l'Empire d'Al'Malaq et symbolise la richesse et le pouvoir de cette civilisation.<br/><br/>La ville est divisée en trois parties distinctes : la vieille ville, le faubourg sud et le faubourg nord. La vieille ville est le centre historique de la cité, où se trouvent les monuments les plus anciens, les temples et les palais de l'Empereur. C'est ici que se concentrent l'essentiel de la vie culturelle et religieuse de la cité.<br/><br/>Les deux faubourgs sont reliés à la vieille ville par une grande avenue bordée d'arbres, qui s'étend sur plusieurs kilomètres. Cette avenue est la principale artère de la ville, où se croisent les cortèges impériaux, les processions religieuses et les convois marchands. Elle est bordée de statues en bronze représentant les héros de l'Empire et de fontaines ornées de mosaïques."
    },
    {
      "title": "Désert de Khamsin",
      "type": "texte",
      "royaume": "AlMalaq",
      "lien": "68",
      "image": "https://i.imgur.com/wOMXnjT.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 197,
      "y": 775,
      "description": "Le désert de Khamsin est un paysage aride et hostile, dominé par des dunes de sable et des rochers escarpés. Les tempêtes de sable sont fréquentes et constituent un danger pour les voyageurs imprudents. Cependant, cette région abrite une faune et une flore étonnamment diversifiées. Les communautés nomades qui habitent ces terres ont développé des techniques de chasse, de cueillette et d'élevage spécifiques à cet environnement extrême pour y survivre.<br/><br/>Entre Evren et le village des éleveurs se trouve une oasis, un havre de paix où les voyageurs peuvent se reposer et se ravitailler en eau. Cependant, le désert est également sujet aux éléments naturels tels que la foudre ou les vents violents, qui peuvent causer des dommages considérables à l'infrastructure des communautés nomades."
    },
    {
      "title": "Havre des éléments",
      "type": "zone rp",
      "royaume": "AlMalaq",
      "lien": "69",
      "image": "https://i.imgur.com/xpn3665.jpg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 78,
      "y": 655,
      "description": "Le Havre des Éléments est un lieu de culte sacré pour les seigneurs élémentaires, sous un plateau entouré de falaises rocheuses et enveloppé de végétation luxuriante. Au centre de ce sanctuaire se dressent quatre trônes majestueux, sculptés dans la pierre et ornés de symboles représentant les quatre éléments primordiaux : l'eau, le feu, l'air et la terre. Jadis, ces trônes servaient de lieu de réunion pour les seigneurs élémentaires, où ils discutaient des affaires importantes de leur royaume.<br/><br/>Cependant, le Havre des Éléments est aujourd'hui laissé à l'abandon, envahi par la nature et oublié des seigneurs élémentaires qui ne s'y réunissent plus. La végétation a recouvert les trônes et les falaises environnantes, mais malgré cela, le Havre des Éléments demeure un lieu fascinant et mystique, chargé de l'histoire et de la culture des seigneurs élémentaires. Sa puissance élémentaire en fait un endroit difficile d'accès, mais pour ceux qui parviennent à le découvrir, c'est un sanctuaire qui laisse une impression durable sur leur esprit."
    },
    {
      "title": "Village des Éleveurs",
      "type": "zone rp",
      "royaume": "AlMalaq",
      "lien": "70",
      "image": "https://i.imgur.com/ew0IDwM.jpg",
      "dangerosité": "4",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 138,
      "y": 877,
      "description": "Le village des éleveurs se situe dans la région sud-ouest d'Al'malaq. Comme son nom l'indique, ce petit village est principalement habité par des éleveurs de créatures magiques, une tradition qui remonte à plusieurs siècles. Les villageois sont fiers de leur capacité à élever et à former des créatures anciennes, qui ont toujours peuplé les terres de feu où le village est implanté.<br/><br/>Le village lui-même est relativement modeste, avec des maisons en bois conçues pour résister aux chaleurs et des rues sableuses. Les habitations sont disposées autour d'un petit marché central, où les éleveurs vendent leurs produits, notamment des potions, des poudres, des peaux de bêtes, des œufs et une grande variété de familiers. Les villageois sont accueillants et chaleureux, et se font un plaisir de partager leur savoir-faire avec les visiteurs."
    },
    {
      "title": "École Militaire",
      "type": "zone rp",
      "royaume": "AlMalaq",
      "lien": "71",
      "image": "https://i.imgur.com/nC3LeVl.jpg",
      "dangerosité": "0",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 274,
      "y": 577,
      "description": "L'école militaire d'Al'Malaq est une institution prestigieuse pour les jeunes soldats qui aspirent à servir leur royaume avec honneur et dévouement. Située sur une île isolée à la périphérie de l'empire, cette école est réputée pour sa rigueur et son excellence. Les bâtiments sont imposants, construits en pierre avec des dômes en forme de bulbe, caractéristiques de l'architecture locale. Les couleurs vives des tissus utilisés pour les tentes et les drapeaux apportent une touche de gaieté à l'environnement autrement austère. Les intérieurs des bâtiments sont également remarquables, avec des décorations élaborées et des motifs complexes qui rappellent l'histoire et la culture de l'île.<br/><br/>La formation à l'école militaire est rigoureuse et exigeante, comprenant une formation physique et mentale intensive, ainsi que l'apprentissage des arts de la guerre. Les soldats sont également formés à la survie dans le désert et aux techniques de survie en cas d'attaques surprises. Malgré la difficulté du programme, les soldats ont des temps de repos pour se détendre et profiter de la vie. Les installations de l'école militaire comprennent des terrains de sport, des jardins luxuriants et des salles de repos où les soldats peuvent se détend"
    },
    {
      "title": "Fulguroforge",
      "type": "zone rp",
      "royaume": "AlMalaq",
      "lien": "72",
      "image": "https://i.imgur.com/7yWLTll.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 133,
      "y": 748,
      "description": "La Fulguro-Forge d'Al'Malaq, nichée au cœur des montagnes escarpées du nord-ouest, est un lieu imprégné d'une aura mystique et puissante, grâce aux nombreux éclairs qui frappent régulièrement les montagnes. Les forgerons qui y travaillent sont considérés comme les meilleurs du royaume, et ils sont chargés de créer les armes emblématiques d'Al'Malaq.<br/><br/>Malgré la nature hostile de l'environnement, la Fulguro-Forge est un lieu de travail fascinant et impressionnant. Le bâtiment ressemble plus à un temple qu'à une forge, avec son architecture imposante et ses sculptures complexes. L'intérieur de la forge est tout aussi impressionnant, luxueux et coloré, empli d’une culture et d’une histoire riche appartenant aux élémentaires d’antan.<br/><br/>Pour les forgerons qui travaillent à la Fulguro-Forge, chaque jour est un défi. Ils doivent non seulement surmonter les obstacles naturels, mais aussi travailler dans un environnement rempli d'énergie électrique. Mais pour ceux qui réussissent à maîtriser ces éléments, les récompenses sont immenses. Les armes créées ici sont considérées comme les meilleures du royaume, et chaque guerrier rêve d'en posséder une."
    },
    {
      "title": "Oasis des Reflets Profonds",
      "type": "lieu d’intérêt",
      "royaume": "AlMalaq",
      "lien": "68",
      "image": "https://i.imgur.com/tHUMF5W.jpeg",
      "dangerosité": "3",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 260,
      "y": 836,
      "description": "L'Oasis des Reflets Profonds, autrefois le royaume d'Amir Al-Bahr, le Seigneur de l'Eau, est le paisible foyer du Palais des Moussons plongé dans les profondeurs d'Al'Malaq. Enveloppée dans une aura de majesté, cette oasis est la plus vaste de tout l'empire, offrant une vision presque envoûtante d'une étendue d'eau qui semble fusionner avec les océans lointains.<br/><br/>Il attire un flot continu de visiteurs et de voyageurs, tous attirés par sa beauté enchanteresse et son aura mystique. C'est un lieu où les gens se rassemblent, où les caravanes s'arrêtent pour se ressourcer, et où les esprits peuvent se détendre sous l'ombrage paisible des palmiers qui bordent les rives. Les eaux calmes et cristallines reflètent le ciel d'un bleu infini, offrant une vision de tranquillité à ceux qui s'y attardent."
    },
    {
      "title": "Cimetière des perdus",
      "type": "lieu d’intérêt",
      "royaume": "AlMalaq",
      "lien": "68",
      "image": "https://i.imgur.com/dJffEMN.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 116,
      "y": 804,
      "description": "Le Cimetière des Perdus est un lieu très connu des Malaqiis, car on dit que si vous vous égarez dans le désert, c'est là que vous finirez par aboutir. Entre les prédateurs d'aujourd'hui, les charognards, les bandits, et les monstres titanesques qui ont autrefois parcouru ce désert et qui, heureusement pour nous, se sont éteints.<br/><br/>Si nous excluons les bêtes et les individus cherchant à disparaître, nous ne trouvons que du sable et des squelettes de créatures inconnues. En fait, à l'exception des plus grands et des plus puissants prédateurs, même les animaux évitent cette zone. Il est impossible d'y amener des montures, pour une raison inconnue, elles feront tout en leur pouvoir pour s'en éloigner. Plusieurs scientifiques ont tenté de s'y rendre pour effectuer des relevés et récupérer des morceaux de squelettes de créatures étranges, mais tout objet technologique semble devenir défaillant et cesser de fonctionner là-bas.<br/><br/>Par conséquent, ces scientifiques ont essayé d'envoyer des individus pour qu'ils ramènent les échantillons directement chez eux. Au fil du temps, le nom du Cimetière des Monstres est devenu le Cimetière des Perdus, et de moins en moins de personnes ont accepté de s'y rendre. Les courageux qui ont réussi à revenir ne sont revenus qu'avec moins que ce qu'ils avaient initialement. À quoi bon alors ?"
    },
    {
      "title": "La tour du coeur",
      "type": "lieu d’intérêt",
      "royaume": "AlMalaq",
      "lien": "67",
      "image": "https://i.imgur.com/240p1wR.jpg",
      "dangerosité": "0",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 279,
      "y": 657,
      "description": "La Tour du Cœur est en réalité un élément qui a été ajouté au port sur ordre de l'empereur Aldynn. Elle comprend une immense cour d'où l'on peut voir l'eau et le vent s'engouffrer, créant des courants dans lesquels il vaut mieux éviter de se baigner. La tour est orientée de manière à ce que le soleil frappe l'immense cadran doré, fournissant ainsi l'heure sur l'eau et la pierre de la cour. Bien que la zone soit ouverte au public et puisse être visitée, l'intérieur de la tour elle-même est interdit d'accès pour la plupart des gens : mais avec de belles paroles, une petite visite accompagnée est peut-être possible.<br/><br/>Le Khan est même considéré comme le gardien de la tour, même si c'est purement symbolique, la tour appartenant en réalité à l'empereur. Cette tour est le lieu où se déroule le dernier défi de l'épreuve des Éléments Éternels, le défi du Cœur, et il s'agit du seul endroit de défi connu. Peu de gens ont osé tenter de forcer l'entrée, car comme il s'agit d'une construction érigée par l'ancien empereur Aldynn, lui donnant un aspect sacré et très respecté.<br/><br/>La tour est cependant également connue pour attirer l'attention. Faite d'or et de pierre blanche, elle est un véritable joyau visuel, et la nuit, une immense flamme est allumée à son sommet, servant ainsi de phare pour les navigateurs."
    },
    {
      "title": "Arsenal Impérial",
      "type": "lieu d’intérêt",
      "royaume": "AlMalaq",
      "lien": "67",
      "image": "https://i.imgur.com/vVisEDO.jpeg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 371,
      "y": 703,
      "description": "Là où l'académie militaire voit émerger de brillants esprits ainsi que des âmes courageuses prêtes à servir et où la Fulguroforge permet de donner naissance à d'innombrables oeuvres d'arts alliant magie élémentaire et technologie permettant de contenir ces grands pouvoirs, l'Arsenal se pose en troisième membre d'un triumvirat fondant les bases de la puissance Malaqi. De fait, c'est en ce site clé que sont imaginés, construits et mis à flots les plus merveilleux vaisseaux ayant jamais fendus les océans n'en déplaise aux ingénieurs noctems dont les créations n'ont aucune âme et sont des plus hideuses.<br/><br/>Ici, les charpentiers de marine associent leurs grands esprits à certains homologues de la Fulguroforge afin de permettre à la flotte impériale de disposer de vaisseaux de guerre toujours performant et surtout toujours plus ingénieux et novateur dans leur usage ainsi que leur conception, car il n'y a après tout aucune raison de ne point user des avantages tactiques que les secrets du pays offrent. Cales sèches, entrepôts divers, rades et autres sites clés forment ainsi l'ensemble des lieux qui officie autant comme chantier naval à grande échelle vomissant sans cesse des embarcations que comme port en lui même, permettant à chaque bâtiment de mouiller mais aussi de venir quérir un abris afin que sa coque soit réparée et ses divers composants maintenus, ce hors de portée du courroux imprévisible des éléments.<br/><br/>A ce titre, les architectes impériaux ont ainsi donnés naissance à une authentique merveille qu'est le Cothon, un ensemble de docks couverts circulaires formés de plusieurs cercles et s'imposant comme le coeur du complexe, laissant les cales sèches, ateliers, forges et autres composantes jouter le tout ce à l'ombre d'imposant remparts abritant aussi plusieurs casernes, là où veille au grain la soldatesque et notamment l'infanterie de Marine qui tiens ses quartiers avec l'Amirauté au plus près de ses outils lui permettant d'imposer la puissance impériale sur les flots.<br/><br/>L'activité en ces lieux est ainsi telle que l'on pourrait croire qu'il s'agit d'une ville dans la ville, la faute certainement aux aller et venues nombreuses bien que rigoureusement contrôlés des marchands venant approvisionner la chaîne de production, des ouvriers à l'oeuvre sur la charpente et des divers portefaix nécessaires au transport et déplacement des innombrables denrées transitant chaque jour sur ces lieux."
    },
    ////////////////////////////////////////////////////////////////////////
    /////////////////// CLARA NOCTE
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Munditia",
      "type": "capitale",
      "royaume": "ClaraNocte",
      "lien": "54",
      "image": "https://i.imgur.com/is9TEd1.jpg",
      "dangerosité": "2",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1705,
      "y": 620,
      "description": "Les rues pavées de la ville, ombragées par des arbres centenaires, offrent une atmosphère paisible et distinguée. Dans le calme presque hypnotique, seules les festivités nobles brisent parfois la quiétude et l'élégance aristocratique de la ville ouest. Les résidents des hautes sphères sociales parcourent les rues argentées, échangeant sur les affaires communes, conférant à ces voies un semblant d'animation.<br/><br/>La massivité de la Caserne de l'Inquisition assure une présence rassurante, veillant sur l'ordre et la sécurité des deux cités. Les demeures nobles, revêtant des teintes argentées, bleutées et violettes, accompagnées d'éléments elfiques, se dressent avec une finesse exquise, leurs jardins privés reflétant la grandeur de leur histoire.<br/><br/>Chaque pierre, chaque symbole gravé, chaque statue dans les rues célèbre la fierté elfique, narrateur silencieux de leur passé, de leur art et de leur héritage. Munditia, à travers ses ruelles et ses demeures, révèle l'âme des elfes, pérennisant la splendeur du passé et l'élégance intemporelle, faisant de Clara Nocte un écrin de majesté elfique."
    },
    {
      "title": "Lava Proditores",
      "type": "capitale",
      "royaume": "ClaraNocte",
      "lien": "56",
      "image": "https://i.imgur.com/3lnZHJw.jpg",
      "dangerosité": "3",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1910,
      "y": 560,
      "description": "Lava Proditores, ville dynamique, fusionne l'élégance victorienne au steampunk avec une exubérance saisissante. Ses rues, bordées de bâtiments imposants, révèlent une architecture où matériaux nobles et mécanismes ingénieux se marient dans une harmonie imposante. Les détails complexes et les rouages mouvants ornent chaque façade, créant un spectacle fascinant.<br/><br/>Le panorama urbain étouffe parfois dans ce dédale où les rues, aux allures similaires, semblent s'enchevêtrer. Des vapeurs émanant des usines et des mécanismes industrieux imprègnent l'air d'une atmosphère envoûtante et unique. Au sein de la ville se dresse un aérodrome où reposent majestueusement les aéronefs, symboles du progrès au cœur de cette jungle d'architecture et de technologie.<br/><br/>Centre névralgique de la classe moyenne de Clara Nocte, Lava Proditores est le berceau des automates, témoins éclatants de la prouesse technologique régionale. Les matériaux nobles, entrelacés aux mécanismes complexes, confèrent à cette cité une grandeur à la fois imposante et mystérieuse, où la beauté de l'ingénierie se mêle à la fascination pour le progrès."
    },
    {
      "title": "Iter Caedis",
      "type": "capitale",
      "royaume": "ClaraNocte",
      "lien": "58",
      "image": "https://i.imgur.com/hXdPVhA.jpg",
      "dangerosité": "6",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 1872,
      "y": 690,
      "description": "Iter Caedis, ville sinistre et sordide, se niche entre deux monts jumeaux, émergeant tel un labyrinthe vertical, un cauchemar urbain figé dans un équilibre précaire. Cette cité, antre de la criminalité, évoque une verticalité oppressante, ses multiples niveaux de bâtiments s'entremêlant dans un enchevêtrement de structures. Les cheminées d'usines crachent des volutes de fumée noire, tandis que des câbles suspendus tracent des lignes dans le ciel grisâtre, conférant à cet univers une esthétique brutale et industrielle.<br/><br/>Les habitants, contraints à une vie précaire au milieu des tuyaux brûlants et des carcasses de bâtiments délabrés, errent dans un dédale de rues étroites et sinueuses. Les murs lézardés et les fenêtres barricadées de planches de bois décrivent un tableau de délabrement et d'abandon. Les rues, jonchées de débris et de cadavres, exacerbent l'atmosphère pesante et anxiogène, où la survie est une lutte quotidienne.<br/><br/>Iter Caedis, par son esthétique sale et décrépite, évoque une ville en décomposition constante, où règne une brutalité oppressante. Les graffitis souillent les murs, les échoppes vendent des biens douteux, transformant cette métropole en une toile lugubre d'obscurité et de désolation, semblant vouée à sombrer dans les ténèbres à tout moment."
    },
    {
      "title": "Temple de la Nuit",
      "type": "zone rp",
      "royaume": "ClaraNocte",
      "lien": "59",
      "image": "https://i.imgur.com/wQo6J0K.jpg",
      "dangerosité": "0",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "sacrée",
      "x": 1917,
      "y": 300,
      "description": "Sur une île mystérieuse au large de la côte de Clara Nocte, se dresse le majestueux Temple de la Nuit, érigé pour honorer la Lune Sainte. Enveloppée d'une brume épaisse et énigmatique. Les pierres blanches du temple se dressent avec fierté, contrastant contre le paysage sombre, ornées de motifs elfiques complexes, témoignant de son raffinement artisanal.<br/><br/>Les gardiens elfiques, figés en statues sentinelles à l'entrée, accueillent les visiteurs alors qu'ils approchent des imposantes portes. À l'intérieur, le hall principal s'illumine d'une douce lueur, laissant des reflets argentés danser sur les murs. Des autels, parés de joyaux précieux, honorent les différents aspects de la Lune Sainte. Revêtus de robes de soie blanche, les prêtres elfiques se tiennent prêts à guider et servir les pèlerins.<br/><br/>Au centre, un bassin cristallin scintille sous les rayons d'une lumière céleste filtrant à travers le dôme de verre. Des salles plus petites s'ouvrent vers des jardins intérieurs où fleurissent des plantes exotiques nocturnes. Les chambres luxueuses offrent des vues imprenables sur les étoiles et l'océan sombre, créant un sanctuaire serein où les visiteurs peuvent méditer et trouver réconfort sous la protection de leur déesse."
    },
    {
      "title": "Champs d'Argent",
      "type": "zone rp",
      "royaume": "ClaraNocte",
      "lien": "55",
      "image": "https://i.imgur.com/dms3sXW.jpg",
      "dangerosité": "3",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1770,
      "y": 850,
      "description": "Les Champs d'Argent émergent tels un joyau rural au sein des vastes plaines de Clara Nocte, embrassés par la majestueuse forêt voisine. Ce paisible village agricole respire la quiétude au cœur de cette contrée où règne un éternel crépuscule. Les terres fertiles, labourées par des générations de fermiers habiles, offrent une profusion de cultures prospères malgré le climat nocturne perpétuel.<br/><br/>Entouré par une nature indomptée, ce havre de paix incarne la simplicité et la sérénité pour ses habitants. Les traditions agricoles y sont vénérées, laissant entrevoir un respect profond pour la terre nourricière. Les Champs d'Argent rayonnent comme une lueur d'espoir au sein d'une région souvent agitée, offrant un refuge où l'harmonie entre l'homme et la nature prévaut.<br/><br/>L'appellation du village tire son origine des arbres aux écorces d'un blanc éclatant et de la teinte azurée de l'herbe qui tapisse les alentours. Les Champs d'Argent représentent ainsi un témoignage vivant de la beauté naturelle préservée, un précieux écrin où la vie simple s'épanouit au sein d'une nature généreuse et respectée."
    },
    {
      "title": "Port Noctem",
      "type": "lieu d’intérêt",
      "royaume": "ClaraNocte",
      "lien": "57",
      "image": "https://i.imgur.com/6sOm7vk.jpg",
      "dangerosité": "3",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 1565,
      "y": 600,
      "description": "Le port de Clara Nocte se dresse majestueusement au nord-ouest du royaume, une vaste étendue maritime où convergent toutes les marchandises. Cette plaque tournante commerciale, empreinte d'une aura mystérieuse nocturne, demeure le cœur battant de l'économie régionale. Dans ce lieu crucial, où les échanges commerciaux s'entremêlent, les frontières sont rigoureusement surveillées, témoignant de la sécurité stricte dans cette enclave maritime.<br/><br/>Le port de Clara Nocte se présente comme un théâtre animé, où le flux incessant de marchandises rencontre la vigilance et le contrôle strict des frontières, dans un décor fascinant mêlant tradition et innovation, entre ombres nocturnes et éclats de progrès."
    },
    {
      "title": "Port du temple de la Nuit",
      "type": "lieu d’intérêt",
      "royaume": "ClaraNocte",
      "lien": "59",
      "image": "https://i.imgur.com/YUTEA9j.jpg",
      "dangerosité": "1",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "bénie",
      "x": 1855,
      "y": 450,
      "description": "Le port religieux menant au Temple de la Nuit se présente comme une annexe discrète du grand port maritime de Clara Nocte. Modeste et fonctionnel, ce petit port revêt une importance singulière, étant le point de départ exclusif des voyageurs se dirigeant vers le temple sacré. Une navette régulière assure ce court trajet de 20 minutes toutes les heures, offrant ainsi un lien essentiel entre les fidèles et le lieu de culte.<br/><br/>L'architecture elfique imprègne cet endroit à petite échelle, mais l'aspect utilitaire prédomine dans sa conception. Malgré sa modestie, le port religieux évoque une aura particulière, marquant le début du cheminement spirituel vers le Temple de la Nuit. C'est là, dans cette modeste mais déterminante structure, que commence le voyage vers la communion et la dévotion au sein de l'éternelle obscurité de Clara Nocte."
    },
    ////////////////////////////////////////////////////////////////////////
    /////////////////// ANANDA
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Amsupolis",
      "type": "capitale",
      "royaume": "Ananda",
      "lien": "61",
      "image": "https://i.imgur.com/nCFW2rC.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 688,
      "y": 860,
      "description": "La ville d'Amsupolis est un lieu à la fois fascinant et angoissant. À première vue, on peut admirer l'architecture majestueuse et imposante qui se dresse devant soi. Les bâtiments sont faits de pierre, avec des colonnes et des arcs élégants, et ornés de sculptures délicates. Les rues sont étroites et sinueuses, créant un labyrinthe mystérieux qui semble inviter à l'exploration. Mais si l'on s'attarde un peu plus longtemps, on peut sentir une étrange présence qui imprègne la ville, un sentiment d'oppression qui pèse sur les épaules.<br/><br/>Les rues sont éclairées par de petites lanternes qui jettent une lueur vacillante sur les murs de pierre. Les façades des bâtiments sont souvent couvertes de mousse, témoignant du climat humide de la ville. Les fenêtres sont souvent petites, créant une ambiance sombre et mystérieuse. La ville semble presque figée dans le temps, avec peu de signes de vie moderne.<br/><br/>Cependant, il y a encore des endroits à explorer, notamment les tréfonds d'Amsupolis. Là, dans les profondeurs de la ville, se trouve une chapelle ensevelie, découverte récemment, qui renferme la statue de trois Sirènes. Cette découverte a suscité un grand intérêt chez les habitants de la ville, qui ont cherché à percer les secrets de cette chapelle perdue. Mais ceux qui s'aventurent dans les tréfonds doivent être prêts à affronter les dangers qui les guettent."
    },
    {
      "title": "Tour Galate",
      "type": "zone rp",
      "royaume": "Ananda",
      "lien": "62",
      "image": "https://i.imgur.com/IVqoDDU.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "gangrénée",
      "x": 613,
      "y": 809,
      "description": "La Tour Galate est un lieu sinistre et inquiétant au cœur duquel vivent les Anarkhias, des êtres humanoïdes déchus qui ont succombé à la tentation des ténèbres. Les Anarkhias ont élu domicile dans la tour, où ils se consacrent à des pratiques obscures et impies, cherchant à étendre leur influence maléfique sur le monde entier. Ils sont accompagnés des damnés, des êtres maudits qui ont été corrompus par la magie de la tour et qui ont choisi de se rallier aux Anarkhias.<br/><br/>La Tour Galate est l'incarnation même de la corruption et de la perversion. Elle se dresse fièrement dans le paysage, sombre et imposante, une véritable insulte à la beauté naturelle du monde. Les maudits ont investi les lieux, transformant la tour en leur forteresse personnelle. Ils y ont aménagé des salles de torture et de rituels impies, ainsi que des cachots où ils gardent captives leurs victimes."
    },
    {
      "title": "Cultures sanguines",
      "type": "zone rp",
      "royaume": "Ananda",
      "lien": "63",
      "image": "https://i.imgur.com/GrHg8Pn.jpg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "gangrénée",
      "x": 887,
      "y": 923,
      "description": "Les cultures sanguines sont un lieu sinistre et corrompu où les émissaires de la Tour Galate pratiquent leur magie noire pour faire pousser des plantes et des créatures maléfiques. Ils ont réussi à maîtriser la magie du sang pour altérer la nature et créer des hybrides monstrueux. Le sol de cette parcelle de terrain est imprégné de sang de sacrifices rituels, ce qui confère une énergie ténébreuse à la terre, permettant une croissance rapide et malsaine des plantes.<br/><br/>Les plantes qui poussent dans les cultures sanguines sont cauchemardesques et dangereuses. Certaines sont recouvertes d'épines acérées qui peuvent transpercer la peau des voyageurs imprudents. D'autres sont carnivores, attirant leurs proies avec de fausses fleurs avant de les dévorer vivantes.Une partie de ces plantes sont le résultat de croisements génétiques entre des animaux sauvages et des espèces démoniaques, donnant naissance à des hybrides violents et terrifiants.<br/><br/>Les maudits utilisent des sortilèges et des poisons pour protéger leur domaine et ne laissent personne entrer sans permission. Les cultures sanguines sont un rappel effrayant du pouvoir corrompu de la tour Galate et un avertissement pour ceux qui chercheraient à s'opposer à eux."
    },
    {
      "title": "Territoire des bêtes impies",
      "type": "texte",
      "royaume": "Ananda",
      "lien": "7",
      "image": "https://i.imgur.com/LMMgEXu.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "gangrénée",
      "x": 1179,
      "y": 869,
      "description": "Il règne ici une atmosphère oppressante, enveloppant le paysage d'une brume rosée qui limite la visibilité et rend l'exploration dangereuse. Le vent souffle constamment dans cette plaine, apportant avec lui une odeur putride et nauséabonde qui remplit les narines de quiconque ose respirer.<br/><br/>Les rares arbustes qui ont réussi à survivre ont des feuilles fanées et brunes, semblables à des mains squelettiques s'accrochant désespérément à la vie dans cette terre maudite. C'est un lieu où l'on n'entend que les cris des bêtes impies qui hurlent et grognent dans la nuit. Les rares aventuriers qui ont survécu à cette région ont décrit une sensation de malaise constant, comme si quelque chose d'horrible était tapi dans l'obscurité, attendant le moment opportun pour les attaquer."
    },
    {
      "title": "Ruines du Barrage d'argent",
      "type": "zone rp",
      "royaume": "Ananda",
      "lien": "65",
      "image": "https://i.imgur.com/yoislBm.jpg",
      "dangerosité": "6",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 1177,
      "y": 966,
      "description": "Le Grand Barrage d'Argent est une construction imposante qui s'étend sur plusieurs kilomètres. Il était constitué de murs massifs en pierre argentée, renforcés par des colonnes du même matériau. De hauts remparts crénelés s'élevaient sur toute la longueur du barrage, surmontés de tours de guet qui permettaient aux elfes de patrouiller en permanence et de surveiller tout mouvement suspect.<br/><br/>Le barrage a été construit dans le but de bloquer le passage entre Ananda et Clara Nocte, et il remplit cette fonction avec succès depuis des siècles. Les elfes chargés de sa surveillance sont des guerriers aguerris, entraînés pour défendre leur territoire et empêcher toute intrusion. Les voyageurs qui tentent de franchir le barrage sans autorisation risquent leur vie, car les elfes ne prennent pas les intrusions à la légère et n'hésitent pas à faire usage de la force si nécessaire.<br/><br/>Depuis l'an 84, le grand Barrage d'Argent n'est plus que l'ombre de lui-même, un trou béant ayant percé le mur du barrage pour le rendre inutilisable."
    },
    {
      "title": "Catacombes d’Amsupolis",
      "type": "lieu d’intérêt",
      "royaume": "Ananda",
      "lien": "61",
      "image": "https://i.imgur.com/Dt7SPk5.jpeg",
      "dangerosité": "5",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 686,
      "y": 920,
      "description": "Les obscures et tortueuses catacombes d’Amsupolis étendent leurs dédales ténébreux sous la cité, gardant farouchement leurs secrets oubliés. Récemment, émergea des flots une chapelle ensevelie, abritant une sculpture vénérée représentant trois sirènes énigmatiques. Cette découverte a attisé la curiosité des citadins, incitant à percer les mystères enfouis dans ces couloirs souterrains.<br/><br/>Cependant, ces profondeurs restent un péril mortel, malgré l'effervescence révolutionnaire. Des créatures hostiles hantent ces ombres impénétrables, dissuadant quiconque de s'aventurer sans préparation adéquate. L'air dense et vicié, difficilement respirable, imprègne l'atmosphère de ces souterrains, imposant une prudence extrême à tout explorateur téméraire.<br/><br/>Ces antres oubliés détiennent un passé enfoui, une histoire voilée par les ténèbres, captivant l'imagination et l'intrigue de ceux osant braver l'obscurité pour révéler les mystères embusqués sous les Catacombes d’Amsupolis."
    },
    {
      "title": "Cathédrale enfouie",
      "type": "lieu d’intérêt",
      "royaume": "Ananda",
      "lien": "79",
      "image": "https://i.imgur.com/SNGJsNw.jpeg",
      "dangerosité": "6",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 975,
      "y": 870,
      "description": "Au cœur des marais corrompus, émerge de manière majestueuse la silhouette envoûtante d'une cathédrale enfouie, partiellement submergée par les eaux salées. Sa structure imposante, moitié noyée dans ces marais inhospitaliers, demeure un témoignage poignant d'un passé glorieux. Malgré l'abandon et la décrépitude, sa beauté intemporelle persiste, défiant le temps qui passe. Les vitraux, encore flamboyants malgré les années, diffusent des éclats de couleur qui dansent à travers les ténèbres environnantes.<br/><br/>Les légendes murmurent que cette cathédrale aurait été le lieu des premiers mariages royaux, mais ces récits, plongés dans l'oubli, demeurent impossibles à vérifier. Ce sanctuaire est impénétrable, suscitant la vénération des âmes pieuses qui se recueillent et prient devant, mais sans espoir d'y entrer.<br/><br/>Ce vestige immergé, gardien silencieux d'histoires oubliées, incarne la grandeur évanouie d'une époque révolue, captivant les rêves et l'imagination de ceux qui osent s'aventurer aux abords de ses eaux troubles."
    },
    {
      "title": "Marécitum",
      "type": "lieu d’intérêt",
      "royaume": "Ananda",
      "lien": "79",
      "image": "https://i.imgur.com/iDXbwJp.jpg",
      "dangerosité": "4",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 805,
      "y": 881,
      "description": "Marécitum est un campement situé au milieu des marécages d’Ananda, à l’Ouest des cultures sanguines. Il bénéficie d’une sécurité accrue en raison des dangers environnants et des gardes y patrouillent en permanence. Sa particularité est qu’il occupe un territoire bordé de marécages prônes au pourrissement de la flore. Une plante encore méconnue émet des vapeurs euphorisantes qui poussent la population à faire preuve d’une extrême chaleur à l’encontre de chaque individu, sédentaires comme voyageurs. Le campement offre un havre de paix momentanément afin qu’ils puissent se requinquer après une longue route, trop égarés des rares villages de la région corrompue.<br/><br/>Le campement est composé d’une quinzaine de tentes dont une un peu plus élégante que les autres appartement au chef, un homme particulièrement avare qui a jeté son dévolu sur les pauvres gens en détresse et les dépouille sans vergogne en échange d’une promesse d’accueil. Une auberge faite de bric et de broc anime sa place centrale et une source d’eau à quelques pas permet aux habitants de se désaltérer au moindre besoin ; au prix de maux digestifs voire de maladies. Bien que l’aspect délabré des constructions puisse en rebuter plus d’un, elles subsistent étonnamment dans le temps et ne devraient pas souffrir des jugements hâtifs. Elles se renouvellement fréquemment lorsqu’un individu décide de rester au sein de la communauté, mais il n’est pas si simple de l’intégrer ! Le chef du campement assigne chaque semaine à plusieurs de ses loyaux sous-fifres de gagner Amsupolis afin de se ravitailler en nourriture, étant donné qu’ils ne peuvent pas cultiver eux-mêmes.<br/><br/>Attention cependant, car au sein du campement erre un homme dit fou par les occupants de Marécitum. Personne ne connait son identité, et il n’hésite pas à importuner les voyageurs. Il maintient qu’il est un rescapé de la tour Galate et a échappé de justesse à la mort…<br/><br/>Ici, il n’y a aucune discrimination. Chacun est le bienvenu, tant qu’il montre patte blanche et possède quelques liges à dépenser dans sa besace. Ledit aubergiste du camp est connu pour offrir discrètement des vivres aux voyageurs mal en point, attisant le courroux du chef qui refuse d’aider les nécessiteux gratuitement.<br/><br/>Gare aux fauteurs de trouble, les gardes n’hésiteront pas à réprimer toute menace au bon maintien de la vie des occupants de Marécitum ainsi que leurs visiteurs."
    },
    ////////////////////////////////////////////////////////////////////////
    /////////////////// NEUTRE
    ////////////////////////////////////////////////////////////////////////
    {
      "title": "Le Nid",
      "type": "zone rp",
      "royaume": "Neutre",
      "lien": "82",
      "image": "https://i.imgur.com/2SK0gQM.jpg",
      "dangerosité": "6",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 110,
      "y": 405,
      "description": "Située non loin des côtes de Vollheim, l'île du nid est un caillou désertique et enneigé, abritant une maigre forêt d'arbres morts congelés par le froid. Elle est entourée d'une mer agitée et de falaises abruptes, ce qui en fait un endroit difficile d'accès.<br/><br/>Au sommet de la plus grande colline de l'île se dresse Le Nid, un château utilisé aujourd'hui par une confrérie de chevaliers saints aux desseins plus que douteux. Cette place forte donne son nom à l'île. Les voyageurs décrivent l'île comme invivable et prétendent que le château est laissé à l'abandon, sans aucune âme qui y vit. Ainsi, l'ordre des chevaliers sacrés fait office de légende en Arathia et beaucoup réfutent leur existence. La forteresse en elle-même est imposante et semble avoir été construite avec une grande attention aux détails de défense. Elle est composée de plusieurs niveaux, chacun étant protégé par des murs épais et des tours de guet.<br/><br/>La Table des Cinq, qui est l'autorité suprême du Nid, se réunit dans une grande salle du conseil située au sommet de la forteresse. Cette salle est faiblement décorée mais ornée de symboles des cinq aspects de la chasse. C'est également ici que les nouveaux membres de l'ordre sont accueillis et où ils reçoivent leur armure symbolique.<br/><br/>Globalement, l'île est lugubre, avec une ambiance sombre et sinistre qui correspond bien aux objectifs extrémistes de l'ordre des Chevaliers Saints."
    },
    {
      "title": "Volcan de Pyrothos",
      "type": "zone rp",
      "royaume": "Neutre",
      "lien": "60",
      "image": "https://i.imgur.com/o7arpYU.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 50,
      "y": 560,
      "description": "Le volcan de Pyrothos est une île volcanique hostile où la nature se montre impitoyable. Des volcans fumants se dressent au-dessus de paysages dévastés et rocailleux, témoins de la violence des éruptions passées. La fumée toxique qui s'échappe des cratères rend l'air irrespirable, et les cendres recouvrent tout sur leur passage, étouffant la vie végétale et animale.<br/><br/>L'île est entourée d'une mer agitée où les vagues viennent se briser sur les rochers acérés, rappelant sans cesse la dangerosité de ce lieu. Les rares bateaux qui passent à proximité prennent soin de s'en éloigner, craignant d'être engloutis par les courants marins puissants.<br/><br/>Malgré tout, il y a quelque chose d'attirant en ces lieux. Les légendes racontent que des richesses incalculables se cachent sous les cendres et la lave, des artefacts anciens témoins d'une civilisation disparue depuis longtemps. D'autres encore prétendent que l'île serait habitée par des esprits malins qui cherchent à attirer les voyageurs égarés pour les sacrifier à leur sombre dessein."
    },
    {
      "title": "Tour de Sylve",
      "type": "zone rp",
      "royaume": "Neutre",
      "lien": "75",
      "image": "https://i.imgur.com/k6rVuAT.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 316,
      "y": 400,
      "description": "Au nord de la Mer de Sylve, on y trouve la nouvelle Tour de Sylve, un lieu suspect qui inquiète ses trois grands voisins. Un champ de force protège son accès, et nul ne peut pénétrer sur les terres entourant le grand pilier mystérieux. Quelques braves s'y sont risqués, mais tous sont repartis bredouilles en constatant que tout ce qui entre en contact avec ce champ de force est renvoyé en sens inverse. En raison de la présence de la Tour, les eaux l'entourant sont également très occupées par les flottes d'Al'Malaq et d'Arvandor, surveillant tout ce qui s'en approche, de près ou de loin."
    },
    {
      "title": "Mer de Sylve",
      "type": "texte",
      "royaume": "Neutre",
      "lien": "75",
      "image": "https://i.imgur.com/k6rVuAT.jpg",
      "dangerosité": "4",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "neutre",
      "x": 450,
      "y": 660,
      "description": "S'étalant entre Vollheim, Al'Malaq et Arvandor, la mer de Sylve est infestée par la piraterie et renferme un grand nombre d'îlots sauvages. Agitée mais moins salée, cette mer ne se mélange pas avec sa voisine, les Eaux Sombres, créant une séparation visuelle entre leurs deux couleurs : de son côté, la mer de Sylve, est bien plus bleue et lumineuse."
    },
    {
      "title": "Eaux Sombres",
      "type": "texte",
      "royaume": "Neutre",
      "lien": "82",
      "image": "https://i.imgur.com/hLLQv4O.jpg",
      "dangerosité": "7",
      "dangerIndicatorHTML": generateDangerIndicator("0"),
      "levelBalance": "corrompue",
      "x": 1100,
      "y": 727,
      "description": "Les Eaux Sombres, étreignant la mer entre Cerah et Ananda, sont une toile sinistre d'obscurité salée. Leur surface, impénétrable et profonde, regorge de mystères et d'horreurs marines. Les courants tourbillonnants s'enchevêtrent, capturant avec voracité tout ce qui tente de les défier. Une densité anormale et une obscurité profonde créent un labyrinthe marin inhospitalier, noyant les intrus dans une nuit éternelle.<br/><br/>Les routes commerciales maritimes entre l'est et l'ouest d'Arathia sont paralysées par la réputation sinistre des Eaux Sombres, suscitant des récits de navires disparus sans laisser de trace. Un problème impactant directement la révolution qui cherche à s'armer contre la Tour Galate, sur les terres d'Ananda."
    },


    ]
  };

  // Mise à jour de chaque objet de localisation avec sa représentation visuelle du niveau de dangerosité
data.locations.forEach(location => {
    location.dangerIndicatorHTML = generateDangerIndicator(location.dangerosité);
  });
